-- 010_activity_reporting_fields.sql

ALTER TABLE activities 
ADD COLUMN IF NOT EXISTS activity_category VARCHAR(50) DEFAULT 'Standalone',
ADD COLUMN IF NOT EXISTS is_external_ngo BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS organization_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS avenues TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS focus_areas TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS activity_expenses NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cash_contribution NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS in_kind_contribution NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS participants INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS beneficiaries INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS volunteers INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS volunteer_hours INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS submit_for_publication BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_activity BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS cover_image TEXT;

-- For other tables like orientations, we can just alter them to match the UI if they are missing fields
ALTER TABLE orientations
ADD COLUMN IF NOT EXISTS name VARCHAR(255),
ADD COLUMN IF NOT EXISTS venue VARCHAR(255),
ADD COLUMN IF NOT EXISTS start_time TIME,
ADD COLUMN IF NOT EXISTS end_time TIME,
ADD COLUMN IF NOT EXISTS orientation_type VARCHAR(50);

ALTER TABLE installations
ADD COLUMN IF NOT EXISTS name VARCHAR(255),
ADD COLUMN IF NOT EXISTS start_time TIME,
ADD COLUMN IF NOT EXISTS end_time TIME;

ALTER TABLE meetings
ADD COLUMN IF NOT EXISTS title VARCHAR(255),
ADD COLUMN IF NOT EXISTS venue VARCHAR(255),
ADD COLUMN IF NOT EXISTS start_time TIME,
ADD COLUMN IF NOT EXISTS end_time TIME,
ADD COLUMN IF NOT EXISTS meeting_type VARCHAR(50);

ALTER TABLE dovs
ADD COLUMN IF NOT EXISTS title VARCHAR(255);
